import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'

const Home: NextPage = () => {
  fetch("/api/test1")
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        </main>
    </div>
  )
}

export default Home
