# Generated by Django 4.1.2 on 2022-10-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortened', models.CharField(max_length=20)),
                ('actual', models.URLField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('visits', models.IntegerField()),
            ],
        ),
    ]
